name: Build and Release EXEs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  actions: write

env:
  EXE_REPO: DaSonOfPoseidon/exeFiles

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - id: extract_version_job_scraper
        shell: pwsh
        run: |
          $text = Get-Content -Raw -Encoding UTF8 utils.py
          if ($text -match '(?m)^\s*__version__\s*=\s*["'']([^"'']+)["'']') {
            Write-Output "VERSION_JOB_SCRAPER=$($matches[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } else {
            throw "Version not found in utils.py"
          }

      - id: extract_version_spreader
        shell: pwsh
        run: |
          $text = Get-Content -Raw -Encoding UTF8 spreader.py
          if ($text -match '(?m)^\s*__version__\s*=\s*["'']([^"'']+)["'']') {
            Write-Output "VERSION_SPREADER=$($matches[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } else {
            throw "Version not found in spreader.py"
          }

      - name: Build JobScraper executable
        run: pyinstaller JobScraper.spec

      - name: Build ButterKnife executable
        run: pyinstaller ButterKnife.spec

      # Tag and release for JobScraper
      - name: Create and push tag for JobScraper
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          TAG="v${{ env.VERSION_JOB_SCRAPER }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists, skipping push"
          else
            git tag -a "$TAG" -m "Release version $TAG"
            git push origin "$TAG"
          fi

      - name: Create or update GitHub Release for JobScraper
        id: create_release_job_scraper
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION_JOB_SCRAPER }}
          name: Release v${{ env.VERSION_JOB_SCRAPER }}
          body: Automated release of JobScraper.exe version v${{ env.VERSION_JOB_SCRAPER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JobScraper EXE to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION_JOB_SCRAPER }}
          files: dist/JobScraper.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger exeFiles update for JobScraper
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ env.EXE_REPO }}
          event-type: exe_update
          client-payload: |
            {
              "exe_name": "JobScraper.exe",
              "version": "${{ env.VERSION_JOB_SCRAPER }}",
              "release_repo": "JobScraper"
            }

      # Tag and release for ButterKnife
      - name: Create and push tag for ButterKnife
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          TAG="v${{ env.VERSION_SPREADER }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists, skipping push"
          else
            git tag -a "$TAG" -m "Release version $TAG"
            git push origin "$TAG"
          fi

      - name: Create or update GitHub Release for ButterKnife
        id: create_release_spreader
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION_SPREADER }}
          name: Release v${{ env.VERSION_SPREADER }}
          body: Automated release of ButterKnife.exe version v${{ env.VERSION_SPREADER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ButterKnife EXE to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION_SPREADER }}
          files: dist/ButterKnife.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger exeFiles update for ButterKnife
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ env.EXE_REPO }}
          event-type: exe_update
          client-payload: |
            {
              "exe_name": "ButterKnife.exe",
              "version": "${{ env.VERSION_SPREADER }}",
              "release_repo": "TaskScraper"
            }